### ISSUE TITLE
SMS Support?

### ISSUE THREAD

**Issue by Legionof7** [EveripediaNetwork/wagmi-magic-connector#5] opened 2022-05-31 20:58 UTC
- **I'm submitting a ...**
  [ ] bug report
  [ x] feature request
  [ ] question about the decisions made in the repository
  [ ] question about how to use this project

- **Summary**
Hi! Thanks for building this, super useful. Was wondering when SMS support was planned to be built in? Is there something Magic doesn't expose that's necessary?

**Comment by Legionof7** [comment] 2022-06-09 21:58
https://github.com/EveripediaNetwork/wagmi-magic-connector/pull/6

Built it within our dev team!

**Comment by kesar** [comment] 2022-06-10 18:00
nice one! we will review it soon and merge :) as a suggestion just leave the issue open till PR gets merged. You can add in PR description the word "Fixes https://github.com/EveripediaNetwork/wagmi-magic-connector/issues/5" and it will automatically close this issue on merge. 

https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

great work!

**Comment by RankJay** [comment] 2022-06-11 16:21
@kesar, can you publish it to npm too, in order for us to use it?

**Comment by kesar** [comment] 2022-06-14 09:06
> @kesar, can you publish it to npm too, in order for us to use it?

sure, sorry for late reply 👍🏻 

I guess @Royal-lobster I think we forgot to publish it, perhaps we can add a pipeline in gh to auto publish new versions, it sounds like a fun thing to do :))

We could review & merge your last PR refactoring and then work in that pipeline for future iterations (and that way we have the pipeline ready if we build other npm packages for the community 🔥 )

**Comment by Royal-lobster** [comment] 2022-06-14 09:26
@RankJay Published the changes in 0.4.0 release !

**Closed** 2022-06-14 09:32 UTC

**Comment by RankJay** [comment] 2022-06-14 15:43
@Royal-lobster and @kesar I think, it is not working, the issue is around frontend.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/53647573/173619628-4b295c6e-912a-4a9b-86c0-7a21bb249f93.png">

**Comment by Royal-lobster** [comment] 2022-06-14 15:48
@RankJay we made the SMS login feature opt in so it doesn't disturb the current implementations. pass the ```enableSMSLogin``` option to connector options to enable sms login

```javascript
const connector = new MagicConnector({
  options: {
    apiKey: YOUR_MAGIC_LINK_API_KEY, //required
    enableSMSLogin: true,
    oauthOptions : {
      providers: ['facebook', 'google', 'twitter'],
      callbackUrl: 'https://your-callback-url.com', //optional
    };
  },
})
```

**Comment by RankJay** [comment] 2022-06-14 15:55
Ahh, I see thank you for this. You mind, if I add this to README doc for others' reference.
